# Generated by Django 3.0.7 on 2020-06-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_cmdb_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb_asset',
            name='comments',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cmdb_asset',
            name='login_u_p',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备登录信息'),
        ),
        migrations.AlterField(
            model_name='cmdb_asset',
            name='os_software_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='软件&系统版本'),
        ),
        migrations.AlterField(
            model_name='cmdb_asset',
            name='produce',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备型号'),
        ),
        migrations.AlterField(
            model_name='cmdb_asset',
            name='service_contract',
            field=models.CharField(blank=True, max_length=30, verbose_name='设备维保服务联系方式'),
        ),
        migrations.AlterField(
            model_name='cmdb_asset',
            name='warranty_expiration',
            field=models.CharField(blank=True, max_length=30, verbose_name='设备维保时间'),
        ),
    ]
