# Generated by Django 3.0.7 on 2020-06-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20200608_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb_asset',
            name='device_type',
            field=models.CharField(choices=[('router', '路由器'), ('switch', '交换机'), ('switch-stack', '交换机堆叠'), ('server', '服务器'), ('voice_video', '音视频设备'), ('other', '其他')], max_length=20),
        ),
    ]
