# Generated by Django 3.0.7 on 2020-06-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20200609_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb_asset',
            name='device_type',
            field=models.CharField(choices=[('router', '路由器(router)'), ('switch', '交换机(switch)'), ('switch-stack', '交换机堆叠(switch-stack)'), ('server', '服务器(server)'), ('voice_video', '音视频设备(voice_video)'), ('other', '其他(voice_video)'), ('app_server', '应用服务(app_server)')], max_length=30),
        ),
    ]
