# Generated by Django 3.0.7 on 2020-06-10 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20200610_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdb_asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='SN must be none NULL....', regex='^\\S*$')]),
        ),
    ]
