# Generated by Django 3.0.7 on 2021-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0009_ip_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_monitor',
            name='monitor_or_not',
            field=models.BooleanField(choices=[(True, 'enable'), (False, 'disable')], default=False, verbose_name='设备IP是否监控'),
        ),
        migrations.AlterField(
            model_name='ip_monitor',
            name='sent_or_not',
            field=models.BooleanField(choices=[(True, '已发送'), (False, '未发送')], default=False, verbose_name='告警邮件是否发送'),
        ),
    ]
